### PR TITLE
chore(deps): bump http from 0.13.4 to 1.1.0

### PR DESCRIPTION
**Pull request by msarkrish**
This PR fixes this #7 issue.

This PR upgraded minimum dart sdk version into 3.0.0 and upgraded http version to 1.0.0

### CODE REVIEW

**Comment by zigapovhe** [comment]
@msarkrish Can you bump that to the latest http version(1.1.0)? @myConsciousness Can this be merged after that? Thanks

**Comment by zigapovhe** [comment]
@msarkrish And collection package's version shouldn't be 1.17.2 as flutter_test uses 1.17.1 in current latest stable SDK (3.10.5), and pub get will fail.

**Comment by msarkrish** [comment]
Sure @zigapovhe , I will update

**Comment by msarkrish** [comment]
@zigapovhe For me pub get is getting success with collection 1.17.2 . 
If I missed something, let me know, I will check and update again. 
image

**Comment by zigapovhe** [comment]
That's interesting. What flutter version are you using?

**Comment by msarkrish** [comment]
@zigapovhe  I'm using flutter 3.10.5
image

**Comment by myConsciousness** [comment]
Hi @msarkrish, sorry for late reply! This issue will be fixed on #10 .

**Pull request closed without merging**
