### PR TITLE
improve regex split

### PR DESCRIPTION
**Pull request by ymelois**
Matches commas that separates cookies if there is plain json as value.

https://regex101.com/r/YW3Qu7

### CODE REVIEW

**Comment by myConsciousness** [comment]
Hi @sehnryr !

Thanks for your contribution :)

And I have confirmed that the existing test fails. 
Is it possible to improve your fix in a way that passes this test?

**Comment by myConsciousness** [comment]
@sehnryr 

Oops, this failure is due to coverage workflow, I will fix this so please wait a bit! :)

**Comment by myConsciousness** [comment]
Hi @sehnryr !

I fixed coverage workflow and we still can get failures on unit test, it seems the date is not splitted correctly, can you fix it?

```
00:04 +0 -1: Test constructor. Test constructor. [E]                                                                                                                                                   
  HttpException: Invalid cookie date tue
  dart:_http                                                     new Cookie.fromSetCookieValue
  package:sweet_cookie_jar/src/sweet_cookie_jar_impl.dart 22:27  new SweetCookieJarImpl.from
  package:sweet_cookie_jar/src/sweet_cookie_jar.dart 59:26       new SweetCookieJar.from
  test/sweet_cookie_jar_test.dart 25:40                          main.<fn>.<fn>
  

00:04 +0 -1: Test find. Test find AWSALB                                                                                                                                                               
00:04 +0 -2: Test find. Test find AWSALB [E]                                                                                                                                                           
  HttpException: Invalid cookie date tue
  dart:_http                                                     new Cookie.fromSetCookieValue
  package:sweet_cookie_jar/src/sweet_cookie_jar_impl.dart [22](https://github.com/myConsciousness/sweet-cookie-jar/runs/6398379241?check_suite_focus=true#step:5:22):27  new SweetCookieJarImpl.from
  package:sweet_cookie_jar/src/sweet_cookie_jar.dart 59:26       new SweetCookieJar.from
  test/sweet_cookie_jar_test.dart 33:40                          main.<fn>.<fn>
  

00:04 +0 -2: Test find. Test find jwt_token                                                                                                                                                            
00:04 +0 -3: Test find. Test find jwt_token [E]                                                                                                                                                        
  HttpException: Invalid cookie date tue
  dart:_http                                                     new Cookie.fromSetCookieValue
  package:sweet_cookie_jar/src/sweet_cookie_jar_impl.dart 22:27  new SweetCookieJarImpl.from
  package:sweet_cookie_jar/src/sweet_cookie_jar.dart 59:[26](https://github.com/myConsciousness/sweet-cookie-jar/runs/6398379241?check_suite_focus=true#step:5:26)       new SweetCookieJar.from
  test/sweet_cookie_jar_test.dart 48:40                          main.<fn>.<fn>
  

00:04 +0 -3: Test find. Test find cookie does not exist.                                                                                                                                               
00:04 +0 -4: Test find. Test find cookie does not exist. [E]                                                                                                                                           
  HttpException: Invalid cookie date tue
  dart:_http                                                     new Cookie.fromSetCookieValue
  package:sweet_cookie_jar/src/sweet_cookie_jar_impl.dart 22:27  new SweetCookieJarImpl.from
  package:sweet_cookie_jar/src/sweet_cookie_jar.dart 59:26       new SweetCookieJar.from
  test/sweet_cookie_jar_test.dart 62:40                          main.<fn>.<fn>
  

00:04 +0 -4: Test findAll. Test findAll csrf_token.                                                                                                                                                    
00:04 +0 -5: Test findAll. Test findAll csrf_token. [E]                                                                                                                                                
  HttpException: Invalid cookie date tue
  dart:_http                                                     new Cookie.fromSetCookieValue
  package:sweet_cookie_jar/src/sweet_cookie_jar_impl.dart 22:[27](https://github.com/myConsciousness/sweet-cookie-jar/runs/6398379241?check_suite_focus=true#step:5:27)  new SweetCookieJarImpl.from
  package:sweet_cookie_jar/src/sweet_cookie_jar.dart 59:26       new SweetCookieJar.from
  test/sweet_cookie_jar_test.dart 78:40                          main.<fn>.<fn>
  

00:04 +0 -5: Test findAll. Test findAll does not exist.                                                                                                                                                
00:04 +0 -6: Test findAll. Test findAll does not exist. [E]                                                                                                                                            
  HttpException: Invalid cookie date tue
  dart:_http                                                     new Cookie.fromSetCookieValue
  package:sweet_cookie_jar/src/sweet_cookie_jar_impl.dart 22:27  new SweetCookieJarImpl.from
  package:sweet_cookie_jar/src/sweet_cookie_jar.dart 59:26       new SweetCookieJar.from
  test/sweet_cookie_jar_test.dart 92:[40](https://github.com/myConsciousness/sweet-cookie-jar/runs/6398379241?check_suite_focus=true#step:5:40)                          main.<fn>.<fn>
```

**Comment by myConsciousness** [comment]
The cookie is created from response based on specification of `Cookie` of `universal_io`, we have to follow this specification :)

https://github.com/myConsciousness/sweet-cookie-jar/blob/99010cbcde7f7acbfe1b420204dcf090bb66ee66/lib/src/sweet_cookie_jar_impl.dart#L22

**Comment by ymelois** [comment]
@myConsciousness The issue was that the `RegExp` was case sensitive, so I fixed that.

**Comment by myConsciousness** [comment]
@sehnryr 

Thanks for your contribution! :)

**Pull request merged**
